In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns

In [8]:
df=pd.read_csv('mymoviedb.csv',lineterminator='\n')

In [14]:
df.head()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9827 entries, 0 to 9826
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   str
 1   Title              9827 non-null   str
 2   Overview           9827 non-null   str
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   int64
 5   Vote_Average       9827 non-null   float64
 6   Original_Language  9827 non-null   str
 7   Genre              9827 non-null   str
 8   Poster_Url         9827 non-null   str
dtypes: float64(2), int64(1), str(6)
memory usage: 4.5 MB

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.describe()

        Popularity    Vote_Count  Vote_Average
count  9827.000000   9827.000000   9827.000000
mean     40.326088   1392.805536      6.439534
std     108.873998   2611.206907      1.129759
min      13.354000      0.000000      0.000000
25%      16.128500    146.000000      5.900000
50%      21.199000    444.000000      6.500000
75%      35.191500   1376.000000      7.100000
max    5083.954000  31077.000000     10.000000

In [16]:
df["Release_Date"]=pd.to_datetime(df["Release_Date"])
print(df["Release_Date"].dtype)

datetime64[us]

In [17]:
df["Release_Date"]=df["Release_Date"].dt.year
print(df["Release_Date"].dtype)

int32

In [19]:
cols=["Overview","Original_Language","Poster_Url"]

In [21]:
df.drop(cols,axis=1,inplace=True)

In [42]:
def categorized_columns(df, col, labels):
    
    desc = df[col].describe()

  
    edges = [desc["min"], desc["25%"], desc["50%"], desc["75%"], desc["max"]]

    
    df[col] = pd.cut(
        df[col], bins=edges, labels=labels, include_lowest=True, duplicates="drop"
    )

    return df

In [43]:
labels=["not_popular","below_average","average","popular"]
categorized_columns(df,"Vote_Average",labels)
df

TypeError: '<' not supported between instances of 'list' and 'float'

In [22]:
df.head()

,Release_Date,Title,Popularity,Vote_Count,Vote_Average,Genre
0,2021,Spider-Man: No Way Home,5083.954,8940,8.3,"Action, Adventure, Science Fiction"
1,2022,The Batman,3827.658,1151,8.1,"Crime, Mystery, Thriller"
2,2022,No Exit,2618.087,122,6.3,Thriller
3,2021,Encanto,2402.201,5076,7.7,"Animation, Comedy, Family, Fantasy"
4,2021,The King's Man,1895.511,1793,7.0,"Action, Adventure, Thriller, War"